name: Combine
on: create

permissions: write-all

jobs:
  combine:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'branch'}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Combine PRs manually
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: ${{ github.event.ref }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git checkout ${{ github.event.ref }}

          prs=$(gh pr list --label "$LABEL" --json headRefName -q '.[].headRefName')

          for branch in $prs; do
            git fetch origin $branch
            git merge --squash origin/$branch || true
          done

          git rm --ignore-unmatch pr_description.md
          git add -A
          git commit -m "Combined PRs with label: $LABEL"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.ref }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[${{ github.event.ref }}] combined!"
          body: ""
          branch: ${{ github.event.ref }}
          base: master
          labels: "bundle"